name: Autobuild

on: [push, repository_dispatch, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Visual Studio
        uses: ilammy/msvc-dev-cmd@v1
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"
      - name: Install Python requirements
        shell: bash
        run: >
          python -m pip install pyinstaller https://cloud.tohka.us/files/panda3d-1.11.0-cp39-cp39-win_amd64.whl &&
          python -m pip install -r requirements.txt
      - name: Build executable
        shell: powershell
        run: >
          pyinstaller --icon=icon.ico --onefile bamtexeditor.spec
      - uses: actions/upload-artifact@v2
        with:
          name: BamTeXEditor
          path: dist/BamTeXEditor.exe